[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ncut_pytorch"
version = "0.0.1"
authors = [
  { name="Huzheng Yang", email="huze.yann@gmail.com" },
]
description = "Normalized Cut and Nyström Approximation"
readme = "README.md"
requires-python = ">=3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Documentation = "https://ncut-pytorch.readthedocs.io/"
Github = "https://github.com/huzeyann/ncut_pytorch/"