site_name: Nyström Normalized Cuts

repo_url: https://github.com/huzeyann/ncut_pytorch
repo_name: ncut_pytorch

theme:
  name: "material"
  features:
    - content.code.copy
    - content.code.select
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    - navigation.indexes
    # - toc.integrate
  icon:
    repo: fontawesome/brands/github
  logo: images/ncut.svg


plugins:
- search
- autorefs
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          show_source: true
          show_root_heading: true
          path: [ncut_pytorch]

nav:
  - Overview & Install: index.md
  - Gallery: gallery.md
  - How NCUT Works: how_ncut_works.md 
  - NCUT and t-SNE/UMAP: compare.md
  - Tutorial 1 - Quick Start: tutorials.md
  - Tutorial 2 - Parameters: parameters.md
  - Tutorial 3 - Add Nodes: add_nodes.md
  - Tutorial 4 - Mixing Data: mixing_data.md
  - Tutorial 5 - Coloring: coloring.md
  - How to Get Better Segmentation: how_to_get_better_segmentation.md
  - Memory Usage: memory_usage.md
  - Speed and Performance: speed_and_performance.md
  - Gradient of NCUT: gradient_of_ncut.md
  - API Reference: api_reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra:
  analytics:
    provider: google
    property: G-8CPZDV5GR1